### ISSUE TITLE
How to load a cycle.travel .gpx route?

### ISSUE THREAD

**Issue by clort81** [junjunguo/PocketMaps#188] opened 2022-05-19 03:26 UTC
I generate a route with https://cycle.travel because it lets me drag the route to avoid heavy roads (for cycling).

I get a .gpx file (XML 1.0 document).   Can i load that route into the program?

I cannot rely on algorithmic route planning as I need to avoid dangerous or illegal (to bike on) roads.

Cheers!

**Comment by Starcommander** [comment] 2022-05-19 14:58
Basically Pocketmaps can load gpx files as Tracking-route.
But currently it is not possible to import such a route directly.
And I am not sure about compatibility.

You can try to copy the gpx file directly into the tracking folder.
Then you can load it on Map-View via Settings(Gear-button) --> Tracking --> load
You can not use navigation for this route, but you can see the route on the map.

In my case the tracking-folder is located in:
**/sdcard/Android/data/com.junjunguo.pocketmaps/files/Download/pocketmaps/tracking/**

**Comment by Starcommander** [comment] 2022-05-19 18:57
You can try to record a tracking-route, just to store an empty route.
Settings(Gear-button) --> Tracking --> start
Then --> stop and --> store the (empty) route.
This maybe creates the directory, that you need.

**Comment by clort81** [comment] 2022-05-20 21:47
> You can try to record a tracking-route, just to store an empty route. Settings(Gear-button) --> Tracking --> start Then --> stop and --> store the (empty) route. This maybe creates the directory, that you need.

Thanks, that created a file 2022-05-20_23-42-07.gpx, which I can then load
but it didnt get put in /sdcard/Android/data/com.junjunguo.pocketmaps/files/Download/pocketmaps/tracking

Tried to find it in adb shell with  find / -name 2022-05-20_23* 2>&1 |grep -v "Permission"  but no results

Creating pocketmaps/tracking and putting my gpx into it doesn't show it in the list under 'load?'

**Comment by Starcommander** [comment] 2022-05-21 00:04
You can also create your own sample, just start tracking, and move around.
Then you should be able to see, store, and load the route.
Maybe you can also attach your **gpx from cycle.travel**, so I can compare the formats when I have time.

**Comment by feelingwalnut** [comment] 2022-05-21 12:16
I can confirm that "load" in "tracking" just loads a history and has no effect on plotting a route. It doesn't enable you to "retrace your steps."

So what is needed for this to work is importing a route for the purpose of navigation from gpx navigation markers.

**Comment by clort81** [comment] 2022-05-21 16:29
Thanks for the responses!

I think that puts the issue into category 'feature request' and can be closed now.  

I found in OsmAnd app, I can load the .gpx route and display it on the moving map.  This serves my requirement.

Attached is a sample .gpx from cycle.travel.

[frankfurt_mainz.gpx.zip](https://github.com/junjunguo/PocketMaps/files/8747963/frankfurt_mainz.gpx.zip)
.

**Comment by Starcommander** [comment] 2022-05-27 12:17
This is now the feature request ;)

@feelingwalnut Did you record your own route and load it again, or imported from an other source?
What exactly do you mean with "just loads a history" ?
I remember, it should load the route, but did not use (and test) the feature very often.

@clort81 Thanks for the example-file, I will compare it with internal files.
By the way: OsmAnd obviously is not completely open source (regarding f-droid hints).

TODO:
- Ensure that loaded gpx files restores the recorded route
- Compare the format of internal and external gpx file, and ensure both are working.
- Add the possibility to load external gpx files

**Comment by feelingwalnut** [comment] 2022-05-27 12:38
I made an account on cycle.travel, figured out how to make a local route through some towns of a known area I have maps installed for, exported the gpx. Imported it to pocketmaps through settings > tracking > load and the analytics screen came up showing attached
![Screenshot_20220527-082321_PocketMaps](https://user-images.githubusercontent.com/34952101/170698819-385ec5ec-edd7-42de-b7e7-aec7df50ce3b.jpg)
However when going to the navigation portion of the app, no route is set, no import is available.

I will test with my own walking route today.
I'll also check if the gpx made by pocketmaps can be imported to cycle.travel andthen back to pocketmaps

**Comment by Starcommander** [comment] 2022-05-27 13:00
@feelingwalnut Thanks for trying. Seems nothing was imported.
If you can also upload the gpx made by pocketmaps, this may help me to find a fix.

**Comment by feelingwalnut** [comment] 2022-05-28 14:35
cycle.travel routes make a gpx file that is using gpx 1.0, it is missing metadata and time, is also missing elevation and time markers on each track point.
pocketmaps includes all this as it is used for the analytics/history and it is also using gpx 1.1
this would explain why the analytics screen shows nothing, which would be the desired outcome.

i forgot to make a small gpx file in pocketmaps while i was away from home. will do and upload later.
i'm going to say all is working as designed but the feature of using a gpx file for navigation purposes is just missing from pocketmaps.

**Comment by Starcommander** [comment] 2022-05-30 19:50
Loading the gpx file from cycle.travel throws an exception.

05-30 21:46:21.834  6629  6629 I GenerateGPX: ---GPX--- --> Tracking-Element: trkpt
05-30 21:46:21.834  6629  6629 I GenerateGPX: ---GPX--- --> Tracking-Lat: 50.11089
05-30 21:46:21.834  6629  6629 I GenerateGPX: ---GPX--- --> Tracking-Lon: 8.68199
05-30 21:46:21.835  6629  6629 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.w3c.dom.Node.getTextContent()' on a null object reference
05-30 21:46:21.837  6629  6629 W System.err: 	at com.junjunguo.pocketmaps.util.GenerateGPX.readGpxFile(:106)
05-30 21:46:21.837  6629  6629 W System.err: 	at com.junjunguo.pocketmaps.map.Tracking.loadData(:97)
05-30 21:46:21.837  6629  6629 W System.err: 	at com.junjunguo.pocketmaps.fragments.AppSettings$10.onClick(:258)

**Comment by Starcommander** [comment] 2022-05-30 20:33
This is because the loader does not tolerate missing tags, like **ele** and **time**
So we have to modify the loader, to support such files.

In contrast, I upload a path recorded by pocketmaps in Austria:
[2022-05-30_21-36-41.zip](https://github.com/junjunguo/PocketMaps/files/8800630/2022-05-30_21-36-41.zip)

**Comment by feelingwalnut** [comment] 2022-05-30 20:38
[tracking.zip](https://github.com/junjunguo/PocketMaps/files/8800643/tracking.zip)
Pocketmaps gpx

Probably late enough to be irrelevant.

**Comment by Starcommander** [comment] 2022-05-30 21:34
I pushed some changes, that allows to load the **gpx file** from **cycle.travel**.
To prevent errors in graph-view I calculate 1sec for each recorded location into the past.
Screenshot:
![Screenshot_20220530-232909_PocketMaps](https://user-images.githubusercontent.com/3107385/171060996-9c22f148-7050-4d95-bc42-cfbd234f8036.png)

**Comment by Starcommander** [comment] 2022-05-30 21:46
@clort81 Are you still interested in this fix?
Otherwise I will release the fix in next version later.

@feelingwalnut Nevertheless, thanks for your record. ;)

TODO: Loading GPX files should be done in background, as the sample loads about 5sec while the screen freezes.

**Comment by clort81** [comment] 2022-07-09 03:59
I'm thrashing between too many projects but it's a great fix! Thanks @Starcommander !

**Comment by Starcommander** [comment] 2023-11-01 22:17
Fixed in V4.0

**Closed by Starcommander** 2023-11-01 22:17 UTC
Labels: Fixed in next Release
