### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by stanrobertdev** [junjunguo/PocketMaps#142] opened 2020-04-09 05:13 UTC
The application currently needs major improvements , but it's on the right path and I really do see it as a google maps alternative in the future.

Improvements like:

- to enable/disable POI
- to enable/disable Buildings Name/Numbers
- to enable/disable Street Name/Numbers
- add speedlimit for the roads (car)
- change between 2d/2.5d views
- change the way you delete a map from swipe to either a "Delete" button next to it or a checkbox and a delete button at the top
- add a fail safe function that if the route has not been stopped on purpose (by clicking the stop route button) then when restarting the application show the last route (in case the application crashes or it's been closed by accidental touch and you are still navigating on that route)
- make so you can't "click-through"/"touch-through" the settings panel/window

**Comment by Starcommander** [comment] 2020-04-14 18:45
Hello @stanrobertdev 
First of all, thanks for the message, and the new ideas.
But i have some considerations to your summary.

Regarding the first three points: Why should anyone want to disable names/numbers/poi?
I think that does not disturb anybody, otherwise more buttons and settings may lead to unwanted complexity.

Similar changing between 2d and 2.5d view.
While navigating (and only while navigating in my opinion) the 2.5d view is worthwhile.
So manually switching makes no sense for me and raises complexity again.

Regarding speedlimits: Would be nice, i agree.
But i am not sure whether i can extract that information from osm-maps.
TODO: Check, whether speed-limits are stored on osm-maps.

What is wrong with swipe for delete?
It is standard in a lot of android apps, and was a lot of work.

Regarding fail safe function. If i press the home-button, then i can bring the app to foreground again with existing route.
TODO: Maybe I can find a way, that reopening the app via icon does bring the existing activity to foreground. (singleton app)
If anyone kills the app, this should not be my task.
And if the app crashes, we should find the reason, and fix it.

Last point: what you mean is, that drag-n-drop on the border-settings-panel affects the map, i think.
This is a little bit annoying.
TODO: Find the cause why the panel does not consume touch events.

Best regards,
Paul

**Comment by Starcommander** [comment] 2020-04-16 22:16
Point 2 is fixed now.
When the map is loaded, it is possible to leave with the android-home-button.
Restarting the app via app-icon results into re-show the same map with route, settings, and so on.

**Comment by Starcommander** [comment] 2020-04-19 12:00
Point 3 is fixed now.
And for Point 1 I created a new task "speed limits" because this is a lot to do.

**Closed by Starcommander** 2020-04-19 12:00 UTC
